name: msksidekick

on:
  push:
    branches: [ develop ]

jobs:
  osx:
    runs-on: macos-latest
    steps:
    - name: checkout msksidekick latest code
      uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: setup python pkg
      run: |
        pip install --upgrade pip
        if [ -f requirements.txt ]; then cat requirements.txt|grep -v pyinstaller|grep -v  setuptools > requirements.txt.tmp; fi
        mv requirements.txt.tmp requirements.txt

    - name: Install Dependencies
      run: |
        CELL=`brew --prefix perl`
        OPENLIB=`brew --prefix openssl`
        CDIR=`pwd`
        export LIBS="-l ${OPENLIB}/lib/libssl.dylib -l ${OPENLIB}/lib/libcrypto.dylib"
        echo $LIBS

        pip3 install --upgrade 'setuptools<45.0.0'
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install --upgrade requests
        pip install --upgrade termcolor
        pip3 install pyinstaller

    - name: Get the version
      id: get_version
      run: |
        if (echo ${GITHUB_REF} | grep "/tags/" > /dev/null); then
          SOURCE_TAG=${GITHUB_REF#refs/tags/}
        elif (echo ${GITHUB_REF} | grep "/heads/" > /dev/null); then
          SOURCE_TAG=${GITHUB_REF#refs/heads/}
        else
          exit 1
        fi
        FILENAME="msksidekick-${SOURCE_TAG}-macos.tar.gz"
        echo "SOURCE_TAG=$SOURCE_TAG" >> $GITHUB_ENV
        echo "FILENAME=$FILENAME" >> $GITHUB_ENV
        pip uninstall jeepney -y
        pip install jeepney
        pyinstaller --onefile --clean --hidden-import pkg_resources msksidekick.py

    - name: rename toolkit
      run: |
        ls -l
        pwd
        ls -l dist/
        mkdir msksidekick
        cp dist/msksidekick msksidekick/msksidekick
        tar czvf ${{ env.FILENAME }} msksidekick/
    - name: Upload OSX
      uses: actions/upload-artifact@v1
      with:
        name: osxbuild
        path: ${{ env.FILENAME }}
