name: msksidekick

on:
  push:
    branches: [ develop ]

jobs:
  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > math-homework.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with:
          name: homework
          path: math-homework.txt

  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v2
        with:
          name: homework
      - shell: bash
        run: |
          value=`cat math-homework.txt`
          expr $value \* 9 > math-homework.txt
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v2
        with:
          name: homework
          path: math-homework.txt

  job_3:
    name: Display results
    needs: job_2
    runs-on: macOS-latest
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v2
        with:
          name: homework
      - name: Print the final result
        shell: bash
        run: |
          value=`cat math-homework.txt`
          echo The result is $value


  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - name: checkout msksidekick code
      uses: actions/checkout@master
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        if [ -f requirements.txt ]; then sed -i '/pyinstaller/d' requirements.txt; fi
        if [ -f requirements.txt ]; then sed -i '/setuptools/d' requirements.txt; fi
        if [ -f requirements.txt ]; then echo "setuptools" >> requirements.txt; fi
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install --upgrade setuptools
        python -V
        python3 -V
    - name: Install pyInstaller
      run: |
        pip install pyInstaller
    - name: Get the version
      id: get_version
      run: |
        if (echo ${GITHUB_REF} | grep "/tags/" > /dev/null); then
          SOURCE_TAG=${GITHUB_REF#refs/tags/}
        elif (echo ${GITHUB_REF} | grep "/heads/" > /dev/null); then
          SOURCE_TAG=${GITHUB_REF#refs/heads/}
        else
          exit 1
        fi
        FILENAME="msksidekick-${SOURCE_TAG}-redhat7.tar.gz"
        echo "SOURCE_TAG=$SOURCE_TAG" >> $GITHUB_ENV
        echo "FILENAME=$FILENAME" >> $GITHUB_ENV
        pip uninstall jeepney -y
        pip install jeepney
        pyinstaller --onefile --clean msksidekick.py
    - name: rename toolkit
      run: |
        ls -l 
        pwd
        ls -l dist/
        mkdir msksidekick
        cp dist/msksidekick msksidekick/msksidekick
        tar czvf ${{ env.FILENAME }} msksidekick/
    - name: Upload centos 7
      uses: actions/upload-artifact@v1
      with:
        name: cento7build
        path: ${{ env.FILENAME }}

  win2019:
    runs-on: windows-latest
    steps:
    - name: checkout msksidekick code
      uses: actions/checkout@master

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade setuptools
        pip install --upgrade pyInstaller
        python -V

    - name: Get the version
      id: get_version
      run: |
        if (${env:GITHUB_REF} -match "tags") {
          $SOURCE_TAG = ${env:GITHUB_REF} -replace 'refs\/tags\/', ''
        } elseif (${env:GITHUB_REF} -match "heads") {
          $SOURCE_TAG = ${env:GITHUB_REF} -replace 'refs\/heads\/', ''
        } else {
          exit 1
        }
        $FILENAME="msksidekick-" + $SOURCE_TAG + "-win64.zip"
        echo "SOURCE_TAG=$SOURCE_TAG" >> ${env:GITHUB_ENV}
        echo "FILENAME=$FILENAME" >> ${env:GITHUB_ENV}
      shell: powershell

    - name: Install OpenSSL
      run: |
        choco install openssl --no-progress
        echo "INCLUDE=C:\\Program Files\\OpenSSL-Win64\\include;%INCLUDE%" >> ${env:GITHUB_ENV}
        echo "LIB=C:\\Program Files\\OpenSSL-Win64\\lib;%LIB%" >> ${env:GITHUB_ENV}

    - name: Compile toolkit
      run: |
        pip uninstall jeepney -y
        pip install jeepney
        pyinstaller --onefile --clean msksidekick.py

    - name: compress toolkit
      run: |
        pwd
        ls dist/
        mkdir msksidekick
        $NAME = "d:\a\msksidekick\msksidekick\${env:FILENAME}"
        echo ${env:FILENAME}
        echo ${NAME}
        cp dist/msksidekick.exe msksidekick/msksidekick.exe
        Compress-Archive -Path .\msksidekick -DestinationPath ${NAME}

    - name: Upload windows
      uses: actions/upload-artifact@v1
      with:
        name: windowsbuild
        path: ${env:FILENAME}

  osx:
    runs-on: macos-latest
    steps:
    - name: checkout msksidekick code
      uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: check python version
      run: |
        python --version
        which python
    - name: setup python pkg
      run: |
        python -V
        pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install --upgrade setuptools
    - name: Get the version
      id: get_version
      run: |
        if (echo ${GITHUB_REF} | grep "/tags/" > /dev/null); then
          SOURCE_TAG=${GITHUB_REF#refs/tags/}
        elif (echo ${GITHUB_REF} | grep "/heads/" > /dev/null); then
          SOURCE_TAG=${GITHUB_REF#refs/heads/}
        else
          exit 1
        fi
        FILENAME="msksidekick-${SOURCE_TAG}-redhat7.tar.gz"
        echo "SOURCE_TAG=$SOURCE_TAG" >> $GITHUB_ENV
        echo "FILENAME=$FILENAME" >> $GITHUB_ENV
        pip uninstall jeepney -y
        pip install jeepney
        pyinstaller --onefile --clean --hidden-import pkg_resources msksidekick.py
    - name: rename toolkit
      run: |
        cd ${CDIR}
        mkdir msksidekick
        cp dist/msksidekick msksidekick/msksidekick
        ls -l ./msksidekick
        tar czvf ${{ env.FILENAME }} msksidekick/msksidekick

    - name: Upload OSX
      uses: actions/upload-artifact@v1
      with:
        name: osxbuild
        path: ${{ env.FILENAME }}
