name: msksidekick

on:
  push:
    branches: [ develop ]

jobs:
  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > math-homework.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with:
          name: homework
          path: math-homework.txt

  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v2
        with:
          name: homework
      - shell: bash
        run: |
          value=`cat math-homework.txt`
          expr $value \* 9 > math-homework.txt
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v2
        with:
          name: homework
          path: math-homework.txt

  job_3:
    name: Display results
    needs: job_2
    runs-on: macOS-latest
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v2
        with:
          name: homework
      - name: Print the final result
        shell: bash
        run: |
          value=`cat math-homework.txt`
          echo The result is $value

  ubuntu-18LTS:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout msksidekick code
      uses: actions/checkout@master
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then sed -i '/pyinstaller/d' requirements.txt; fi
        if [ -f requirements.txt ]; then sed -i '/setuptools/d' requirements.txt; fi
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Remove pyInstaller 4.2
      run: |
        pip install pyInstaller setuptools
    - name: Get the version
      id: get_version
      run: |
        if (echo ${GITHUB_REF} | grep "/tags/" > /dev/null); then
          SOURCE_TAG=${GITHUB_REF#refs/tags/}
        elif (echo ${GITHUB_REF} | grep "/heads/" > /dev/null); then
          SOURCE_TAG=${GITHUB_REF#refs/heads/}
        else
          exit 1
        fi
        FILENAME="msksidekick-${SOURCE_TAG}-redhat7.tar.gz"
        echo "SOURCE_TAG=$SOURCE_TAG" >> $GITHUB_ENV
        echo "FILENAME=$FILENAME" >> $GITHUB_ENV
        pip3 uninstall jeepney -y
        pip3 install jeepney
        pyinstaller --onefile --clean msksidekick.py
    - name: rename toolkit
      run: |
        ls -l 
        pwd
        ls -l dist/
        mkdir msksidekick
        cp dist/msksidekick msksidekick/msksidekick
        tar czvf ${{ env.FILENAME }} msksidekick/
    - name: Upload centos 7
      uses: actions/upload-artifact@v1
      with:
        name: cento7build
        path: ${{ env.FILENAME }}
